### ISSUE TITLE
cannot access '*.xml': No such file or directory

### ISSUE THREAD

**Issue by Jens-dev** [gpupo/actions-phpDocumentor#2]
I try to get the phpDocumentor action working but if I use './' as base directory, the action seems to run in the '.github/workflows/' folder.
If I use '../../' as base directory I get these ourput:

Running phpDocumentor on ../../
PHP Version : 7.4.16
/

Please create phpdoc.xml or phpdoc.dist.xml file
ls: cannot access '*.xml': No such file or directory

But there is a phpdoc.dist.xml in my base directory.

**Comment by gpupo** [comment]
@Jens-dev let me see you Github workflow  config?

**Comment by Jens-dev** [comment]
@gpupo thx fo your response

My .github/workflows/main.yml
looks like

`# phpDocumentor automating

on:
  push:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      directory:
        description: 'Base directory'
        required: true
        default: '../../'
        
jobs:
  createDocu:
    runs-on: ubuntu-latest
    steps:
      - name: PhpDocumentor
        uses: gpupo/actions-phpDocumentor@1.0
        with:
          dir: '../../'
`

**Comment by gpupo** [comment]
maybe "with dir" is the cause ...
can u try a config like https://github.com/uspdev/replicado/blob/master/.github/workflows/PhpDocumentor.yml ?

**Comment by Jens-dev** [comment]
Okay, I give it a try and will report...

**Comment by Jens-dev** [comment]
Nope,... did not solve the problem.

still getting:

## Running phpDocumentor on .
PHP Version : 7.4.16
/github/workspace

Please create phpdoc.xml or phpdoc.dist.xml file
ls: cannot access '*.xml': No such file or directory

looks like it is looking in /github/workspace again

**Comment by gpupo** [comment]
@Jens-dev before the build you need to checkout the project 

```yaml
 - uses: actions/checkout@v2
      with:
        persist-credentials: false
``

**Comment by Jens-dev** [comment]
@gpupo okay, sorry but in GitHub I'm quite new to the actions

where exactly ich have to put the checkout
```yml
# phpDocumentor automating

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      directory:
        description: 'Base directory'
        required: true
        default: './'
        
jobs:
  createDocu:
    runs-on: ubuntu-latest
    steps:
      - name: PhpDocumentor
        uses: gpupo/actions-phpDocumentor@1.0
```

**Comment by gpupo** [comment]
This works:

```yaml
name: Publica a documentação automaticamente no github-pages
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: PhpDocumentor
      uses: gpupo/actions-phpDocumentor@1.0

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs
        CLEAN: true

```

**Comment by Jens-dev** [comment]
Okay now phpDocumentor is running, but it gets stuck while trying to generate the docs.
Some wired twig erros.
Witch template do you use? I was trying the default.

**Comment by gpupo** [comment]
@Jens-dev you can run phpdoc in your localhost and generate the docs ?

**Comment by Jens-dev** [comment]
@gpupo yes I can.

**Comment by gpupo** [comment]
@Jens-dev without any error message I will not be able to help you. You can try tag 1.2 instead 1.0 and let me know what happens

**Comment by Jens-dev** [comment]
@gpupo okay, I will try the 1.2 Version

here ist the error message from 1.0

```
## Running phpDocumentor on .
PHP Version : 7.4.16
/github/workspace
phpDocumentor v3.0.0-rc-94-gafdd4034

Parsing files

  1/48 [>---------------------------]   2%
 29/48 [================>-----------]  60%

Applying transformations (can take a while)
 48/48 [============================] 100%07:50:58 ERROR     [console] An error occurred while using the console. Message: "Template "tags.html.twig" is not defined." ["exception" => Twig\Error\LoaderError { …},"message" => "Template "tags.html.twig" is not defined."]
07:50:58 ERROR     [console] An error occurred while using the console. Message: "Template "tags.html.twig" is not defined." ["exception" => Twig\Error\LoaderError { …},"message" => "Template "tags.html.twig" is not defined."]

In function.html.twig line 59:
                                             
  Template "tags.html.twig" is not defined.  
                                             

project:run [-t|--target [TARGET]] [--cache-folder [CACHE-FOLDER]] [-f|--filename [FILENAME]] [-d|--directory [DIRECTORY]] [--encoding [ENCODING]] [--extensions [EXTENSIONS]] [-i|--ignore [IGNORE]] [--ignore-tags [IGNORE-TAGS]] [--hidden] [--ignore-symlinks] [-m|--markers [MARKERS]] [--title [TITLE]] [--force] [--validate] [--visibility [VISIBILITY]] [--defaultpackagename [DEFAULTPACKAGENAME]] [--sourcecode] [--template [TEMPLATE]] [-s|--setting [SETTING]] [--list-settings] [--parseprivate] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-c|--config [CONFIG]] [--log [LOG]] [-e|--env ENV] [--no-debug] [--] <command>
## Running phpDocumentor on .
PHP Version : 7.4.16
/github/workspace
```

**Comment by Jens-dev** [comment]
@gpupo Version 1.2 is running perfect.

But one last issue is still there.
In my phpdoc.dist.xml I'm defining the docs output folder, but it is not been updated after the action was running.
I believe I'm missing a point, but what?

**Comment by gpupo** [comment]
@Jens-dev try a simple phpdoc.dist.xml like this:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<phpdoc>
  <title>My Project</title>
  <parser>
    <target>docs</target>
  </parser>

  <transformer>
    
    <target>docs</target>
  </transformer>
  <files>
    <directory>src</directory>
    <directory>tests</directory>
  </files>
</phpdoc>
```

**Comment by Jens-dev** [comment]
@gpupo I've tried, but the result is the same.
Is it possible, that I'm missing a step in my YML File. Something like committing the new doc back?

```yml
# phpDocumentor automating
name: Create phpDocumentation on master changes
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
        
jobs:
  createDocu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: PhpDocumentor
      uses: gpupo/actions-phpDocumentor@1.2
```

**Comment by gpupo** [comment]
@Jens-dev you need to create a job to push the changes PhpDocumentor job
like 
```yaml
 - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs
        CLEAN: true
```
